import test from'node:test';import assert from'node:assert/strict';
import{reconcileEvidence}from'../netlify/functions/_evidence-truth.mjs';
import{prioritizeDiagnosis}from'../netlify/functions/_diagnosis-priority.mjs';
import{runtimeCheckFromEvents}from'../netlify/functions/_browser-runtime.mjs';
const NOW=Date.parse('2026-09-03T18:45:00Z');
const check=(id,status,source,observedAt,evidence={})=>({id,label:id,status,detail:`${id} ${status}`,evidence:{source,observedAt,...evidence}});

test('fresh current proof replaces stale contradictory prior proof',()=>{const previous={checks:[check('map.app-railway','FAIL','weaverelay-cross-system','2026-09-03T16:00:00Z')]};const current={checks:[check('map.app-railway','PASS','weaverelay-cross-system','2026-09-03T18:44:00Z')]};const out=reconcileEvidence(current,{previousSnapshot:previous,now:NOW});assert.equal(out.checks[0].status,'PASS');assert.equal(out.checks[0].evidence.truth.winner,'current');assert.equal(out.truthSummary.unresolvedContradictionCount,0)});

test('one weaker fresh probe cannot erase stronger recent proof',()=>{const previous={checks:[check('repair.railway-runtime','FAIL','weaverelay-repair-verification','2026-09-03T18:40:00Z')]};const current={checks:[check('repair.railway-runtime','PASS','weaverelay-live','2026-09-03T18:44:00Z')]};const out=reconcileEvidence(current,{previousSnapshot:previous,now:NOW});assert.equal(out.checks[0].status,'WARN');assert.equal(out.checks[0].evidence.stale,true);assert.equal(out.checks[0].evidence.truth.winner,'previous');assert.equal(out.truthSummary.unresolvedContradictionCount,0)});

test('old failed relationship evidence is demoted instead of driving a repair',()=>{const out=reconcileEvidence({checks:[check('map.railway-supabase','FAIL','weaverelay-cross-system','2026-09-03T16:00:00Z')]},{now:NOW});assert.equal(out.checks[0].status,'WARN');assert.equal(out.checks[0].evidence.truth.statusDemotedFrom,'FAIL');assert.equal(out.truthSummary.staleCount,1)});

test('two independent similarly strong current sources remain unresolved',()=>{const out=reconcileEvidence({checks:[check('a','PASS','weaverelay-cross-system','2026-09-03T18:44:00Z',{claimKey:'production-backend',claimValue:'railway-a',independentSource:'deployed-app'}),check('b','PASS','weaverelay-runtime-payments','2026-09-03T18:44:00Z',{claimKey:'production-backend',claimValue:'railway-b',independentSource:'provider-control-plane'})]},{now:NOW});assert.equal(out.truthSummary.unresolvedContradictionCount,1);assert.equal(out.checks.every(c=>c.status==='WARN'),true);assert.equal(out.checks.every(c=>c.evidence.stale===true),true)});

test('materially stronger independent evidence can resolve a contradiction without deleting the loser',()=>{const out=reconcileEvidence({checks:[check('strong','FAIL','weaverelay-repair-verification','2026-09-03T18:44:00Z',{claimKey:'runtime-state',claimValue:'broken',independentSource:'runtime-verification'}),check('weak','PASS','client-snapshot','2026-09-03T18:44:00Z',{claimKey:'runtime-state',claimValue:'healthy',independentSource:'client-seed'})]},{now:NOW});assert.equal(out.truthSummary.unresolvedContradictionCount,0);assert.equal(out.checks.find(c=>c.id==='strong').status,'FAIL');assert.equal(out.checks.find(c=>c.id==='weak').status,'WARN')});

test('browser runtime failures keep the event observation time for aging',()=>{const out=runtimeCheckFromEvents([{type:'fetch-failure',url:'https://app.example/api',status:500,receivedAt:'2026-09-03T18:44:00Z'}],{now:NOW});assert.equal(out.status,'FAIL');assert.equal(out.evidence.observedAt,'2026-09-03T18:44:00Z')});

test('unresolved truth conflict outranks configuration-changing repairs',()=>{const snapshot={checks:[{id:'map.railway-supabase',status:'FAIL',evidence:{source:'weaverelay-cross-system'}}]};const diagnosis={findings:[{id:'railway-supabase-mismatch',severity:'critical',title:'Change Supabase',evidence:['map.railway-supabase'],provider:'railway',repair:{supported:true,type:'railway-supabase-url',provider:'railway',approvalRequired:true,label:'FIX'}},{id:'evidence-conflict-unresolved',severity:'high',title:'Sources disagree',evidence:[],repair:{supported:false,approvalRequired:true,label:'VERIFY CONFLICT FIRST'}}]};const out=prioritizeDiagnosis(diagnosis,snapshot);assert.equal(out.primaryFinding.id,'evidence-conflict-unresolved')});

test('live diagnose route passes through truth wrapper and priority engine',async()=>{const{readFile}=await import('node:fs/promises');const toml=await readFile(new URL('../netlify.toml',import.meta.url),'utf8'),wrapper=await readFile(new URL('../netlify/functions/diagnose-workspace-truth.mjs',import.meta.url),'utf8');assert.match(toml,/diagnose-workspace-truth/);assert.match(wrapper,/reconcileEvidence/);assert.match(wrapper,/prioritizeDiagnosis/);assert.match(wrapper,/previousSnapshot/);assert.match(wrapper,/restorePriorTruth/)});
