import test from'node:test';import assert from'node:assert/strict';import{buildRunPodAppRelationshipEvidence}from'../netlify/functions/_runpod-app-relationship.mjs';
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json'}});const html=t=>new Response(t,{status:200,headers:{'content-type':'text/html'}});
const selected={status:'PASS',detail:'GitHub source references one workflow.',evidence:{source:'test',workflowSelected:true,selectionProof:'source-reference'},workflow:{'1':{class_type:'WanVaceToVideo',inputs:{}},'2':{class_type:'KSampler',inputs:{}}}};

test('proves exact app to RunPod to ComfyUI target and selected workflow compatibility',async()=>{const fetchImpl=async url=>{const u=String(url);if(u==='https://app.example/')return html('<script>const x="https://studio123-8188.proxy.runpod.net"</script>');if(u.endsWith('/system_stats'))return json({system:{comfyui_version:'0.3.99'},devices:[{}]});if(u.endsWith('/object_info'))return json({CheckpointLoaderSimple:{},KSampler:{},WanVaceToVideo:{},SecretCustomNode:{input:{token:'MUST_NOT_RETURN'}}});throw Error(u)};const out=await buildRunPodAppRelationshipEvidence({workspace:{siteOrigin:'https://app.example/'},runpodInventory:{pods:[{id:'studio123',desiredStatus:'RUNNING',ports:['8188/http']}],endpoints:[]},fetchImpl,workflowDiscovery:selected});assert.equal(out.checks.find(x=>x.id==='map.app-runpod').status,'PASS');assert.equal(out.checks.find(x=>x.id==='map.app-runpod-comfyui').status,'PASS');assert.equal(out.checks.find(x=>x.id==='comfyui.workflow-selection').status,'PASS');assert.equal(out.checks.find(x=>x.id==='comfyui.workflow-compatibility').status,'PASS');const dep=out.checks.find(x=>x.id==='comfyui.dependencies');assert.equal(dep.status,'PASS');assert.equal(dep.evidence.vaceNodePresent,true);assert.equal(JSON.stringify(out).includes('studio123'),false);assert.equal(JSON.stringify(out).includes('MUST_NOT_RETURN'),false)});

test('identifies exact missing workflow model after GitHub selection',async()=>{const workflow={status:'PASS',detail:'selected',evidence:{workflowSelected:true},workflow:{'1':{class_type:'UNETLoader',inputs:{unet_name:'wan2.1_vace_14B_fp16.safetensors'}},'2':{class_type:'KSampler',inputs:{}}}};const fetchImpl=async url=>{const u=String(url);if(u==='https://app.example/')return html('https://studio123-8188.proxy.runpod.net');if(u.endsWith('/system_stats'))return json({system:{},devices:[{}]});if(u.endsWith('/object_info'))return json({UNETLoader:{input:{required:{unet_name:[['other.safetensors']]}}},KSampler:{}});throw Error(u)};const out=await buildRunPodAppRelationshipEvidence({workspace:{siteOrigin:'https://app.example/'},runpodInventory:{pods:[{id:'studio123'}],endpoints:[]},fetchImpl,workflowDiscovery:workflow});const c=out.checks.find(x=>x.id==='comfyui.workflow-compatibility');assert.equal(c.status,'FAIL');assert.equal(c.evidence.missingModelCount,1);assert.deepEqual(c.evidence.missingModelNames,['wan2.1_vace_14B_fp16.safetensors'])});

test('fails when deployed app points to a RunPod target outside connected account',async()=>{const out=await buildRunPodAppRelationshipEvidence({workspace:{siteOrigin:'https://app.example/'},runpodInventory:{pods:[{id:'rightpod'}],endpoints:[]},fetchImpl:async()=>html('https://wrongpod-8188.proxy.runpod.net')});assert.equal(out.checks.find(x=>x.id==='map.app-runpod').status,'FAIL')});
test('warns instead of guessing when app target is not publicly provable',async()=>{const out=await buildRunPodAppRelationshipEvidence({workspace:{siteOrigin:'https://app.example/'},runpodInventory:{pods:[{id:'p1'}],endpoints:[{id:'e1'}]},fetchImpl:async()=>html('<h1>app</h1>')});assert.equal(out.checks.find(x=>x.id==='map.app-runpod').status,'WARN')});
