import{getStore}from'@netlify/blobs';
const store=()=>getStore({name:'weaverelay-browser-runtime',consistency:'strong'});
const clean=(v,n=240)=>String(v??'').replace(/[\r\n\t]+/g,' ').trim().slice(0,n);
const TYPES=new Set(['javascript-error','unhandled-rejection','fetch-failure','xhr-failure','resource-failure']);
const safeUrl=value=>{try{const u=new URL(String(value||''));if(!/^https?:$/.test(u.protocol))return null;u.username='';u.password='';u.search='';u.hash='';return u.toString().slice(0,500)}catch{return null}};
const safeInteraction=value=>{if(!value||typeof value!=='object')return null;const kind=['click','submit'].includes(value.kind)?value.kind:null;if(!kind)return null;return{kind,element:clean(value.element,40)||null,journey:clean(value.journey,80)||null,step:clean(value.step,80)||null,at:clean(value.at,40)||null}};
export function sanitizeRuntimeEvent(input={}){const type=TYPES.has(input.type)?input.type:null;if(!type)return null;const status=Number(input.status);return{type,message:clean(input.message,320)||null,url:safeUrl(input.url),status:Number.isFinite(status)&&status>=0&&status<=599?status:null,interaction:safeInteraction(input.interaction),at:clean(input.at,40)||new Date().toISOString()}}
export function sanitizeRuntimeBatch(input){const items=Array.isArray(input)?input:[input];return items.slice(0,20).map(sanitizeRuntimeEvent).filter(Boolean)}
export function boundedRuntimeWindow(current={},incomingCount,{now=Date.now(),limit=120}={}){const start=Date.parse(current.windowStartedAt||'');const same=Number.isFinite(start)&&now-start<60000,used=same?Math.max(0,Number(current.windowAccepted)||0):0,remaining=Math.max(0,limit-used),accepted=Math.min(Math.max(0,incomingCount||0),remaining);return{accepted,windowStartedAt:same?current.windowStartedAt:new Date(now).toISOString(),windowAccepted:used+accepted,rateLimited:accepted<incomingCount}}
export async function recordRuntimeEvents(workspaceId,events,{now=new Date().toISOString()}={}){const key=`recent/${workspaceId}.json`,current=await store().get(key,{type:'json',consistency:'strong'}).catch(()=>null)||{},window=boundedRuntimeWindow(current,events.length,{now:Date.parse(now)}),acceptedEvents=events.slice(0,window.accepted),prior=Array.isArray(current.events)?current.events:[],merged=[...acceptedEvents.map(e=>({...e,receivedAt:now})),...prior].slice(0,80);await store().setJSON(key,{workspaceId,updatedAt:now,events:merged,windowStartedAt:window.windowStartedAt,windowAccepted:window.windowAccepted});return{accepted:acceptedEvents.length,stored:merged.length,rateLimited:window.rateLimited}}
export function runtimeCheckFromEvents(events,{maxAgeMinutes=60,now=Date.now()}={}){const recent=(events||[]).filter(e=>{const t=Date.parse(e.receivedAt||e.at||'');return Number.isFinite(t)&&now-t<=maxAgeMinutes*60000});if(!recent.length)return{id:'website.browser-runtime',label:'Browser runtime',status:'WARN',detail:'No recent privacy-safe browser runtime evidence is available yet. Install the WeaveRelay runtime observer or wait for a customer browser session.',evidence:{source:'weaverelay-browser-runtime',eventCount:0,windowMinutes:maxAgeMinutes,customerContentRetained:false}};const top=recent[0],journey=top.interaction?.journey,step=top.interaction?.step,where=top.url||'the browser runtime',context=[journey,step].filter(Boolean).join(' → ');return{id:'website.browser-runtime',label:'Browser runtime',status:'FAIL',detail:`${context?`${context}: `:''}${top.type.replaceAll('-',' ')} at ${where}${top.status?` (HTTP ${top.status})`:''}.`,evidence:{source:'weaverelay-browser-runtime',eventCount:recent.length,windowMinutes:maxAgeMinutes,failureType:top.type,url:top.url,status:top.status,journey:journey||null,step:step||null,customerContentRetained:false,formValuesRetained:false,responseBodiesRetained:false,headersRetained:false,cookiesRetained:false}}
export async function browserRuntimeEvidence(workspaceId,{maxAgeMinutes=60,now=Date.now()}={}){const current=await store().get(`recent/${workspaceId}.json`,{type:'json',consistency:'strong'}).catch(()=>null);return{checks:[runtimeCheckFromEvents(current?.events||[],{maxAgeMinutes,now})]}}
