import{getStore}from'@netlify/blobs';
const store=()=>getStore({name:'weaverelay-synthetic-journeys',consistency:'strong'});
const clean=(v,n=160)=>String(v??'').replace(/[\r\n\t]+/g,' ').trim().slice(0,n);
const SAFE_ACTIONS=new Set(['navigate','assert-visible','click-link','click-control','wait-for-url']);
const BLOCKED_HINTS=/(buy|purchase|pay|checkout|order|delete|remove|terminate|cancel|publish|deploy|send|invite|transfer|withdraw|refund|charge|subscribe|sign.?up|create.?account|accept|agree)/i;
const SAFE_METHODS=new Set(['GET','HEAD']);
const SAFE_ID=/^[a-zA-Z0-9._-]{1,80}$/;
const sameOriginPath=v=>{const p=clean(v,300);return p&&p.startsWith('/')&&!p.startsWith('//')&&!p.includes('\\')?p.split('#')[0]:null};
export function normalizeJourney(input={}){const steps=Array.isArray(input.steps)?input.steps:[];return{id:clean(input.id,80)||null,name:clean(input.name,100)||'Synthetic journey',startPath:sameOriginPath(input.startPath)||'/',steps:steps.slice(0,20).map((s,i)=>({index:i+1,action:clean(s?.action,40),selector:clean(s?.selector,240)||null,path:sameOriginPath(s?.path),label:clean(s?.label,100)||null,method:clean(s?.method||'GET',12).toUpperCase()}))}}
export function reviewSyntheticJourney(input={}){const journey=normalizeJourney(input),reasons=[];if(!journey.id||!SAFE_ID.test(journey.id))reasons.push('Journey must have a stable safe id.');if(!journey.steps.length)reasons.push('Journey must contain at least one step.');for(const step of journey.steps){if(!SAFE_ACTIONS.has(step.action))reasons.push(`Step ${step.index} uses blocked action ${step.action||'unknown'}.`);if(!SAFE_METHODS.has(step.method))reasons.push(`Step ${step.index} would use a mutating HTTP method.`);const text=[step.label,step.selector,step.path].filter(Boolean).join(' ');if(BLOCKED_HINTS.test(text))reasons.push(`Step ${step.index} looks financially, destructively, legally, or account-state sensitive.`);if(['navigate','wait-for-url'].includes(step.action)&&!step.path)reasons.push(`Step ${step.index} requires a same-origin path.`);if(['assert-visible','click-link','click-control'].includes(step.action)&&!step.selector)reasons.push(`Step ${step.index} requires a selector.`);if(step.action==='click-control'&&!/data-weaverelay-safe-action/.test(step.selector||''))reasons.push(`Step ${step.index} control click must target an element marked data-weaverelay-safe-action.`)}return{approved:reasons.length===0,mode:'read-only-browser',requiresExplicitApproval:true,allowsFormSubmission:false,allowsTyping:false,allowsMutationRequests:false,allowsPurchases:false,allowsDestructiveActions:false,reasons,journey}}
export function buildSyntheticEvidence(result={}){const status=result.status==='PASS'?'PASS':result.status==='FAIL'?'FAIL':'WARN';const step=result.failedStep||result.lastStep||null;return{id:'website.synthetic-journey',label:'Approved synthetic journey',status,detail:status==='PASS'?`Synthetic journey ${clean(result.name,100)||'approved journey'} completed without a proven browser failure.`:status==='FAIL'?`${clean(result.name,100)||'Approved journey'} failed${step?.label?` at ${clean(step.label,100)}`:''}${result.reason?`: ${clean(result.reason,240)}`:''}.`:'No recent approved synthetic journey result is available.',evidence:{source:'weaverelay-synthetic-browser',journeyId:clean(result.journeyId,80)||null,failedStep:step?{index:Number(step.index)||null,action:clean(step.action,40)||null,label:clean(step.label,100)||null}:null,url:safeResultUrl(result.url),httpStatus:safeStatus(result.httpStatus),javascriptError:Boolean(result.javascriptError),networkFailure:Boolean(result.networkFailure),browserReplayProven:Boolean(result.browserReplayProven),customerContentRetained:false,formValuesRetained:false,responseBodiesRetained:false,cookiesRetained:false,headersRetained:false,mutationRequestsAllowed:false}}}
const safeResultUrl=value=>{try{const u=new URL(String(value||''));if(!/^https?:$/.test(u.protocol))return null;u.username='';u.password='';u.search='';u.hash='';return u.toString().slice(0,500)}catch{return null}};
const safeStatus=v=>{const n=Number(v);return Number.isFinite(n)&&n>=0&&n<=599?n:null};
export async function readJourneyConfig(workspaceId){const value=await store().get(`config/${workspaceId}.json`,{type:'json',consistency:'strong'}).catch(()=>null);return value&&typeof value==='object'?value:{journeys:[]}}
export async function saveJourney(workspaceId,input,{approvedBy}={}){const review=reviewSyntheticJourney(input);if(!review.approved)throw Object.assign(new Error(review.reasons[0]||'Journey failed the safety review.'),{status:409});if(input.explicitApproval!==true)throw Object.assign(new Error('Explicit customer approval is required before a synthetic journey can be saved.'),{status:409});const current=await readJourneyConfig(workspaceId),now=new Date().toISOString(),record={...review.journey,approved:true,approvedAt:now,approvedBy:clean(approvedBy,120)||null,safety:{mode:review.mode,allowsFormSubmission:false,allowsTyping:false,allowsMutationRequests:false,allowsPurchases:false,allowsDestructiveActions:false}};const journeys=[...(current.journeys||[]).filter(j=>j.id!==record.id),record].slice(-10);await store().setJSON(`config/${workspaceId}.json`,{workspaceId,updatedAt:now,journeys});return record}
export async function saveSyntheticResult(workspaceId,result){const safe={workspaceId,journeyId:clean(result.journeyId,80)||null,name:clean(result.name,100)||'Synthetic journey',status:result.status==='PASS'?'PASS':result.status==='FAIL'?'FAIL':'WARN',reason:clean(result.reason,300)||null,failedStep:result.failedStep&&typeof result.failedStep==='object'?{index:Number(result.failedStep.index)||null,action:clean(result.failedStep.action,40)||null,label:clean(result.failedStep.label,100)||null}:null,lastStep:result.lastStep&&typeof result.lastStep==='object'?{index:Number(result.lastStep.index)||null,action:clean(result.lastStep.action,40)||null,label:clean(result.lastStep.label,100)||null}:null,url:safeResultUrl(result.url),httpStatus:safeStatus(result.httpStatus),javascriptError:Boolean(result.javascriptError),networkFailure:Boolean(result.networkFailure),browserReplayProven:result.browserReplayProven===true,ranAt:new Date().toISOString(),customerContentRetained:false,formValuesRetained:false,responseBodiesRetained:false,cookiesRetained:false,headersRetained:false};await store().setJSON(`result/${workspaceId}/${safe.journeyId}.json`,safe);return safe}
export async function readLatestSyntheticEvidence(workspaceId){const config=await readJourneyConfig(workspaceId),journeys=(config.journeys||[]).filter(j=>j.approved===true).slice(0,10);if(!journeys.length)return buildSyntheticEvidence({status:'WARN'});const results=[];for(const j of journeys){const r=await store().get(`result/${workspaceId}/${j.id}.json`,{type:'json',consistency:'strong'}).catch(()=>null);if(r)results.push(r)}if(!results.length)return buildSyntheticEvidence({status:'WARN'});const failed=results.find(r=>r.status==='FAIL');if(failed)return buildSyntheticEvidence(failed);if(results.every(r=>r.status==='PASS'))return{id:'website.synthetic-journey',label:'Approved synthetic journeys',status:'PASS',detail:`${results.length} approved non-destructive browser journey${results.length===1?'':'s'} passed.`,evidence:{source:'weaverelay-synthetic-browser',journeyCount:results.length,browserReplayProven:results.every(r=>r.browserReplayProven===true),mutationRequestsAllowed:false,formValuesRetained:false,responseBodiesRetained:false,cookiesRetained:false,headersRetained:false}};return buildSyntheticEvidence(results[0])}
export function buildRunnerPayload(workspace,journey){const targetOrigin=new URL(workspace.siteOrigin).origin;return{version:1,targetOrigin,journey:{id:journey.id,name:journey.name,startPath:journey.startPath,steps:journey.steps},safety:{sameOriginOnly:true,allowedHttpMethods:['GET','HEAD'],blockMutationRequests:true,blockFormSubmission:true,blockTyping:true,blockFileUpload:true,blockDownloads:true,blockDialogs:true,blockNewWindows:true,clickControlRequiresAttribute:'data-weaverelay-safe-action',retainScreenshots:false,retainResponseBodies:false,retainHeaders:false,retainCookies:false,maxSteps:20,maxRuntimeMs:30000}}}
export async function invokeBrowserRunner(workspace,journey,{fetchImpl=fetch}={}){const runnerUrl=clean(process.env.WEAVERELAY_BROWSER_RUNNER_URL,500),token=clean(process.env.WEAVERELAY_BROWSER_RUNNER_TOKEN,500);if(!runnerUrl||!token)throw Object.assign(new Error('Synthetic browser runner is not configured. WeaveRelay will not claim a replay until a real guarded browser runner is connected.'),{status:409});const payload=buildRunnerPayload(workspace,journey),response=await fetchImpl(runnerUrl,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','user-agent':'weaverelay-synthetic-runner'},body:JSON.stringify(payload),signal:AbortSignal.timeout?AbortSignal.timeout(35000):undefined});const data=await response.json().catch(()=>null);if(!response.ok||!data||data.browserReplayProven!==true)throw Object.assign(new Error('The configured browser runner did not return a proven guarded browser result.'),{status:502});return saveSyntheticResult(workspace.id,{journeyId:journey.id,name:journey.name,status:data.status,reason:data.reason,failedStep:data.failedStep,lastStep:data.lastStep,url:data.url,httpStatus:data.httpStatus,javascriptError:data.javascriptError,networkFailure:data.networkFailure,browserReplayProven:true})}
