import{requireUser}from'./_auth.mjs';
import{requireWorkspace,readConnection,readSecret}from'./_workspace-store.mjs';
import{decryptSecret}from'./_vault.mjs';
import{json,safeError}from'./_http.mjs';
const timeout=ms=>AbortSignal.timeout?AbortSignal.timeout(ms):undefined;
const clean=v=>String(v??'').trim();
async function connectionToken(workspaceId,provider){const c=await readConnection(workspaceId,provider).catch(()=>null);if(!c?.id||c.status==='revoked')return null;const secret=decryptSecret(await readSecret(c.id));return secret?.accessToken||secret?.token||secret?.apiKey||secret?.key||null}
async function railway(token){const query=`query { projects { edges { node { id name services { edges { node { id name serviceInstances { edges { node { latestDeployment { status createdAt } } } } } } } environments { edges { node { id name } } } } } } }`;
 const r=await fetch('https://backboard.railway.com/graphql/v2',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({query}),signal:timeout(9000)}),d=await r.json().catch(()=>({}));if(!r.ok||d.errors)return{ok:false,status:r.status||502};const projects=d.data?.projects?.edges||[];const services=[];for(const p of projects){for(const s of p.node?.services?.edges||[]){const inst=s.node?.serviceInstances?.edges||[],latest=inst.map(x=>x.node?.latestDeployment).filter(Boolean).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];services.push({name:clean(s.node?.name)||'Railway service',deploymentStatus:clean(latest?.status)||'UNKNOWN',deployedAt:latest?.createdAt||null})}}
 return{ok:true,projectCount:projects.length,serviceCount:services.length,services:services.slice(0,12),resourceBodiesRetained:false,variableValuesRetained:false}}
async function stripe(token){const headers={authorization:`Bearer ${token}`};const [bal,web,events]=await Promise.all(['balance','webhook_endpoints?limit=10','events?limit=10'].map(async path=>{const r=await fetch(`https://api.stripe.com/v1/${path}`,{headers,signal:timeout(9000)});return{ok:r.ok,status:r.status,data:await r.json().catch(()=>({}))}}));if(!bal.ok&&bal.status!==403&&bal.status!==401)return{ok:false,status:bal.status};const hooks=web.ok?(web.data?.data||[]):[],ev=events.ok?(events.data?.data||[]):[];return{ok:bal.ok||web.ok||events.ok,balanceReadable:bal.ok,webhookInventoryReadable:web.ok,eventInventoryReadable:events.ok,webhookCount:hooks.length,enabledWebhookCount:hooks.filter(x=>x.status==='enabled').length,recentEventCount:ev.length,recentEventTypes:[...new Set(ev.map(x=>clean(x.type)).filter(Boolean))].slice(0,5),resourceBodiesRetained:false,balanceAmountsRetained:false,endpointUrlsRetained:false,eventPayloadsRetained:false}}
export default async request=>{if(request.method!=='GET')return json(405,{error:'Method not allowed.'});try{const user=await requireUser(request),u=new URL(request.url),workspace=await requireWorkspace(user.id,u.searchParams.get('workspaceId')),provider=clean(u.searchParams.get('provider')).toLowerCase();if(!['railway','stripe'].includes(provider))return json(400,{error:'Provider window is not supported.'});const token=await connectionToken(workspace.id,provider);if(!token)return json(409,{error:`Connect ${provider==='railway'?'Railway':'Stripe'} first.`});const data=provider==='railway'?await railway(token):await stripe(token);if(!data.ok)return json(data.status===401||data.status===403?403:502,{error:`${provider==='railway'?'Railway':'Stripe'} live window is unavailable with the current connection permissions.`});return json(200,{ok:true,provider,mode:'read-only',data})}catch(error){return safeError(error)}};
