import{requireUser}from'./_auth.mjs';
import{requireWorkspace,readConnection,readSecret}from'./_workspace-store.mjs';
import{decryptSecret}from'./_vault.mjs';
import{PROVIDERS}from'./_provider-catalog.mjs';
import{json,safeError}from'./_http.mjs';
const timeout=ms=>AbortSignal.timeout?AbortSignal.timeout(ms):undefined;
const clean=v=>String(v??'').trim();
const headers=token=>({authorization:`Bearer ${token}`,accept:'application/json','user-agent':'weaverelay-provider-window'});
async function connectionToken(workspaceId,provider){const c=await readConnection(workspaceId,provider).catch(()=>null);if(!c?.id||c.status==='revoked')return null;const secret=decryptSecret(await readSecret(c.id));return secret?.accessToken||secret?.token||secret?.apiKey||secret?.key||null}
async function getJson(url,token){const r=await fetch(url,{headers:headers(token),signal:timeout(9000)}),d=await r.json().catch(()=>null);return{ok:r.ok,status:r.status,data:d}}
async function railway(token){const query=`query { projects { edges { node { id name services { edges { node { id name serviceInstances { edges { node { latestDeployment { status createdAt } } } } } } } environments { edges { node { id name } } } } } } }`;const r=await fetch('https://backboard.railway.com/graphql/v2',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({query}),signal:timeout(9000)}),d=await r.json().catch(()=>({}));if(!r.ok||d.errors)return{ok:false,status:r.status||502};const projects=d.data?.projects?.edges||[],services=[];for(const p of projects){for(const s of p.node?.services?.edges||[]){const inst=s.node?.serviceInstances?.edges||[],latest=inst.map(x=>x.node?.latestDeployment).filter(Boolean).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];services.push({name:clean(s.node?.name)||'Railway service',deploymentStatus:clean(latest?.status)||'UNKNOWN',deployedAt:latest?.createdAt||null})}}return{ok:true,projectCount:projects.length,serviceCount:services.length,services:services.slice(0,12),resourceBodiesRetained:false,variableValuesRetained:false}}
async function stripe(token){const [bal,web,events]=await Promise.all(['balance','webhook_endpoints?limit=10','events?limit=10'].map(async path=>{const r=await fetch(`https://api.stripe.com/v1/${path}`,{headers:headers(token),signal:timeout(9000)});return{ok:r.ok,status:r.status,data:await r.json().catch(()=>({}))}}));if(!bal.ok&&bal.status!==403&&bal.status!==401)return{ok:false,status:bal.status};const hooks=web.ok?(web.data?.data||[]):[],ev=events.ok?(events.data?.data||[]):[];return{ok:bal.ok||web.ok||events.ok,balanceReadable:bal.ok,webhookInventoryReadable:web.ok,eventInventoryReadable:events.ok,webhookCount:hooks.length,enabledWebhookCount:hooks.filter(x=>x.status==='enabled').length,recentEventCount:ev.length,recentEventTypes:[...new Set(ev.map(x=>clean(x.type)).filter(Boolean))].slice(0,5),resourceBodiesRetained:false,balanceAmountsRetained:false,endpointUrlsRetained:false,eventPayloadsRetained:false}}
async function vercel(token){const r=await getJson('https://api.vercel.com/v9/projects?limit=12',token);if(!r.ok)return{ok:false,status:r.status};const projects=Array.isArray(r.data?.projects)?r.data.projects:[];return{ok:true,projectCount:projects.length,projects:projects.slice(0,12).map(p=>({name:clean(p?.name)||'Vercel project',framework:clean(p?.framework)||null,updatedAt:p?.updatedAt||null})),projectIdsRetained:false,environmentValuesRetained:false,resourceBodiesRetained:false}}
async function render(token){const r=await getJson('https://api.render.com/v1/services?limit=12',token);if(!r.ok)return{ok:false,status:r.status};const raw=Array.isArray(r.data)?r.data:[],services=raw.map(x=>x?.service||x).filter(Boolean).slice(0,12).map(s=>({name:clean(s?.name)||'Render service',type:clean(s?.type)||clean(s?.serviceType)||'service',suspended:clean(s?.suspended)||null}));return{ok:true,serviceCount:services.length,services,serviceIdsRetained:false,environmentValuesRetained:false,resourceBodiesRetained:false}}
async function cloudflare(token){const r=await getJson('https://api.cloudflare.com/client/v4/user/tokens/verify',token),status=clean(r.data?.result?.status).toUpperCase();return{ok:r.ok&&r.data?.success===true&&status==='ACTIVE',status:r.status,tokenStatus:status||'UNKNOWN',tokenIdRetained:false,accountIdsRetained:false,resourceBodiesRetained:false}}
async function neon(token){const r=await getJson('https://console.neon.tech/api/v2/projects?limit=12',token);if(!r.ok)return{ok:false,status:r.status};const projects=Array.isArray(r.data?.projects)?r.data.projects:[];return{ok:true,projectCount:projects.length,projects:projects.slice(0,12).map(p=>({name:clean(p?.name)||'Neon project',region:clean(p?.region_id)||clean(p?.region)||null,updatedAt:p?.updated_at||null})),projectIdsRetained:false,databaseHostsRetained:false,resourceBodiesRetained:false}}
async function resend(token){const r=await getJson('https://api.resend.com/domains',token);if(!r.ok)return{ok:false,status:r.status};const domains=Array.isArray(r.data?.data)?r.data.data:[];return{ok:true,domainCount:domains.length,verifiedCount:domains.filter(d=>String(d?.status).toLowerCase()==='verified').length,domains:domains.slice(0,12).map(d=>({name:clean(d?.name)||'Resend domain',status:clean(d?.status)||'UNKNOWN',region:clean(d?.region)||null})),domainIdsRetained:false,dnsRecordsRetained:false,resourceBodiesRetained:false}}
const readers={railway,stripe,vercel,render,cloudflare,neon,resend};
export default async request=>{if(request.method!=='GET')return json(405,{error:'Method not allowed.'});try{const user=await requireUser(request),u=new URL(request.url),workspace=await requireWorkspace(user.id,u.searchParams.get('workspaceId')),provider=clean(u.searchParams.get('provider')).toLowerCase(),reader=readers[provider];if(!reader)return json(400,{error:'Provider window is not supported.'});const token=await connectionToken(workspace.id,provider);if(!token)return json(409,{error:`Connect ${PROVIDERS[provider]?.label||provider} first.`});const data=await reader(token);if(!data.ok)return json(data.status===401||data.status===403?403:502,{error:`${PROVIDERS[provider]?.label||provider} live window is unavailable with the current connection permissions.`});return json(200,{ok:true,provider,mode:'read-only',data})}catch(error){return safeError(error)}};
