const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let current=null,workspaces=[],credentialProvider=null;
const HELP={netlify:'Create a Netlify personal access token for this Early Access connection. WeaveRelay uses it only for read-only account/deploy diagnostics.',railway:'Use a Railway account/OAuth token for the Early Access read-only probe. Project/workspace-scoped OAuth is the long-term path.',supabase:'Use a Supabase Management API access token. Prefer a scoped token when your account supports them.',stripe:'Create a Stripe restricted key with Balance → Read only. No write permissions are needed.'};
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'content-type':'application/json',...(options.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed.');return j}
function showLogin(){$('#login').classList.remove('hidden');$('#app').classList.add('hidden')}function showApp(user){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#userEmail').textContent=user.email}
async function session(){const j=await api('/api/auth/session');if(!j.user){showLogin();return null}showApp(j.user);return j.user}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button'),s=$('#loginStatus');b.disabled=true;try{const j=await api('/api/auth/request',{method:'POST',body:JSON.stringify({email:$('#email').value,company:$('#company').value,next:location.pathname+location.search})});s.textContent=j.message}catch(err){s.textContent=err.message}finally{b.disabled=false}};
$('#signout').onclick=async()=>{await api('/api/auth/signout',{method:'POST',body:'{}'});location.replace('/app.html')};
async function loadList(){const j=await api('/api/workspaces');workspaces=j.workspaces||[];$('#workspaceList').innerHTML=workspaces.map(w=>`<button class="workspace-link ${w.id===current?'active':''}" data-id="${esc(w.id)}"><strong>${esc(w.name)}</strong><span>${esc(w.status||'needs_action')}</span></button>`).join('')||'<p class="muted">No apps yet.</p>';document.querySelectorAll('.workspace-link').forEach(b=>b.onclick=()=>openWorkspace(b.dataset.id))}
function statusClass(s){return ['connected','PASS'].includes(s)?'good':['error','revoked','FAIL'].includes(s)?'bad':'warn'}
async function openWorkspace(id){current=id;history.replaceState(null,'',`/app.html?w=${encodeURIComponent(id)}`);await loadList();const j=await api(`/api/workspace?id=${encodeURIComponent(id)}`),w=j.workspace,c=j.connections||{};$('#empty').classList.add('hidden');$('#workspace').classList.remove('hidden');$('#workspaceTitle').textContent=w.name;$('#appName').textContent=w.name;$('#siteOrigin').textContent=w.siteOrigin||'Website URL not set';$('#providers').innerHTML=(w.providers||[]).map(p=>{const live=c[p.id],status=live?.status||p.status||'not_connected',connected=status==='connected';return `<article class="provider-card"><div class="provider-top"><strong>${esc(p.label)}</strong><span class="chip ${statusClass(status)}">${esc(status.replaceAll('_',' '))}</span></div><p>${esc(live?.externalAccountName?`Connected: ${live.externalAccountName}`:(p.detail||'Not connected yet.'))}</p><div class="provider-buttons"><button class="${connected?'ghost':'secondary'} provider-action" data-provider="${esc(p.id)}" data-connected="${connected?'1':'0'}">${connected?'VERIFY LIVE':'CONNECT'}</button>${connected?`<button class="disconnect provider-disconnect" data-provider="${esc(p.id)}">DISCONNECT</button>`:''}</div></article>`}).join('');document.querySelectorAll('.provider-action').forEach(b=>b.onclick=()=>providerAction(b.dataset.provider,b.dataset.connected==='1'));document.querySelectorAll('.provider-disconnect').forEach(b=>b.onclick=()=>disconnectProvider(b.dataset.provider));const flow=w.stackMap?.flow||[];$('#stackMap').innerHTML=flow.length?flow.map((x,i)=>`<span>${esc(x)}</span>${i<flow.length-1?'<i>→</i>':''}`).join(''):'<p class="muted">The map will fill in from your connections.</p>';renderDiagnosis(w.diagnosis)}
function renderDiagnosis(d){if(!d){$('#diagnosis').innerHTML='<p>No diagnosis yet.</p>';return}$('#diagnosis').innerHTML=`<div class="diag-head"><h2>${esc(d.headline)}</h2><span class="chip ${d.status==='healthy'?'good':d.status==='broken'?'bad':'warn'}">${esc(d.status)}</span></div><p>${esc(d.summary)}</p>${(d.findings||[]).map(f=>{const repair=f.repair||{};const open=f.openProvider;return `<article class="finding"><strong>${esc(f.title)}</strong><p>${esc(f.explanation)}</p>${(f.actions||[]).map(a=>`<div class="next">Next: ${esc(a)}</div>`).join('')}<div class="provider-buttons">${repair.supported?`<button class="secondary finding-fix" data-repair="${esc(repair.type||'')}" data-provider="${esc(repair.provider||f.provider||'')}">${esc(repair.label||'FIX IT')}</button>`:`<button class="ghost" disabled>${esc(repair.label||'GUIDED FIX')}</button>`}${open?.url?`<a class="button ghost" href="${esc(open.url)}" target="_blank" rel="noopener noreferrer">${esc(open.label||'OPEN PROVIDER')}</a>`:''}</div></article>`}).join('')||'<p>No cross-system failure was found in the current evidence.</p>'}`;document.querySelectorAll('.finding-fix').forEach(b=>b.onclick=()=>runRepair(b.dataset.repair,b.dataset.provider))}
async function runRepair(type,provider){
  if(type==='reconnect-provider'&&provider){await providerAction(provider,false);return}
  if(type==='railway-supabase-url'){
    const approved=confirm('WeaveRelay will change only Railway SUPABASE_URL for the one production service it can prove belongs to this app. It will use the Supabase project already proven by the deployed app, then read the value back to verify the change. No other Railway variables will be replaced. Approve this repair?');
    if(!approved)return;
    try{const j=await api('/api/repair/railway-supabase',{method:'POST',body:JSON.stringify({workspaceId:current,approved:true})});alert(j.message||'Repair completed.');await api('/api/diagnose',{method:'POST',body:JSON.stringify({workspaceId:current})});await openWorkspace(current)}catch(err){alert(err.message)}
    return;
  }
  alert('This repair is not enabled until its write permission and post-fix verification test are proven safe.')
}
async function disconnectProvider(provider){if(!confirm(`Disconnect ${provider} from this WeaveRelay workspace? The stored encrypted credential will be deleted.`))return;try{await api('/api/provider/disconnect',{method:'POST',body:JSON.stringify({workspaceId:current,provider})});await openWorkspace(current)}catch(err){alert(err.message)}}
async function providerAction(provider,connected){try{if(connected){await api('/api/provider/probe',{method:'POST',body:JSON.stringify({workspaceId:current,provider})});await openWorkspace(current);return}if(provider==='github'){const j=await api('/api/provider/start',{method:'POST',body:JSON.stringify({workspaceId:current,provider})});if(j.authorizationUrl)location.href=j.authorizationUrl;return}credentialProvider=provider;$('#credentialTitle').textContent=`Connect ${provider[0].toUpperCase()+provider.slice(1)}`;$('#credentialHelp').textContent=HELP[provider]||'Enter the least-privilege read-only credential for this provider.';$('#credential').value='';$('#credentialStatus').textContent='';$('#credentialModal').classList.remove('hidden')}catch(err){alert(err.message)}}
$('#credentialForm').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;$('#credentialStatus').textContent='Verifying with the provider…';try{await api('/api/provider/connect-key',{method:'POST',body:JSON.stringify({workspaceId:current,provider:credentialProvider,credential:$('#credential').value})});$('#credential').value='';$('#credentialModal').classList.add('hidden');await openWorkspace(current)}catch(err){$('#credentialStatus').textContent=err.message}finally{b.disabled=false}};
$('#closeCredential').onclick=()=>{$('#credential').value='';$('#credentialModal').classList.add('hidden')};
$('#diagnose').onclick=async()=>{const b=$('#diagnose');b.disabled=true;b.textContent='DIAGNOSING…';try{const j=await api('/api/diagnose',{method:'POST',body:JSON.stringify({workspaceId:current})});renderDiagnosis(j.diagnosis);await openWorkspace(current)}catch(err){alert(err.message)}finally{b.disabled=false;b.textContent='RUN LIVE DIAGNOSIS'}};
const openCreate=()=>$('#modal').classList.remove('hidden');$('#newWorkspace').onclick=openCreate;$('#emptyCreate').onclick=openCreate;$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#workspaceForm').onsubmit=async e=>{e.preventDefault();try{const j=await api('/api/workspace/create',{method:'POST',body:JSON.stringify({name:$('#newName').value,siteOrigin:$('#newOrigin').value})});$('#modal').classList.add('hidden');await loadList();await openWorkspace(j.workspace.id)}catch(err){$('#modalStatus').textContent=err.message}};
async function claimClientTicket(){const q=new URLSearchParams(location.search),ticket=q.get('clientTicket');if(!ticket)return null;try{const j=await api('/api/workspace/claim-client',{method:'POST',body:JSON.stringify({ticket})});history.replaceState(null,'',`/app.html?w=${encodeURIComponent(j.workspaceId)}`);return j.workspaceId}catch(err){if(/Sign in/.test(err.message))return null;alert(err.message);return null}}
(async()=>{const user=await session();if(!user)return;const claimed=await claimClientTicket();await loadList();const id=claimed||new URLSearchParams(location.search).get('w')||workspaces[0]?.id;if(id)await openWorkspace(id)})();
