import http from'node:http';
import{chromium}from'playwright';
const PORT=Number(process.env.PORT||8080),TOKEN=String(process.env.WEAVERELAY_BROWSER_RUNNER_TOKEN||'');
const SAFE_ACTIONS=new Set(['navigate','assert-visible','click-link','click-control','wait-for-url']);
const SAFE_METHODS=new Set(['GET','HEAD']);
const clean=(v,n=240)=>String(v??'').replace(/[\r\n\t]+/g,' ').trim().slice(0,n);
const safePath=v=>{const p=clean(v,300);return p&&p.startsWith('/')&&!p.startsWith('//')&&!p.includes('\\')?p.split('#')[0]:null};
const safeUrl=(origin,path)=>{try{const u=new URL(path,origin);return u.origin===new URL(origin).origin?u.href:null}catch{return null}};
const stepSafe=s=>SAFE_ACTIONS.has(s?.action)&&SAFE_METHODS.has(String(s?.method||'GET').toUpperCase())&&(!['navigate','wait-for-url'].includes(s.action)||safePath(s.path))&&(!['assert-visible','click-link','click-control'].includes(s.action)||clean(s.selector,240))&&(s.action!=='click-control'||/data-weaverelay-safe-action/.test(s.selector||''));
function validate(body){try{const origin=new URL(body?.targetOrigin);if(origin.protocol!=='https:'&&origin.protocol!=='http:')return null;const j=body?.journey,steps=Array.isArray(j?.steps)?j.steps:[];if(!j?.id||!steps.length||steps.length>20||!steps.every(stepSafe))return null;return{origin:origin.origin,journey:{id:clean(j.id,80),name:clean(j.name,100)||'Synthetic journey',startPath:safePath(j.startPath)||'/',steps}}}catch{return null}}
const response=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(data))};
async function run(spec){const browser=await chromium.launch({headless:true});let page,lastStep=null,networkFailure=false,javascriptError=false,httpStatus=null;
 try{const context=await browser.newContext({acceptDownloads:false,serviceWorkers:'block'});page=await context.newPage();page.on('pageerror',()=>{javascriptError=true});page.on('requestfailed',()=>{networkFailure=true});context.on('page',p=>{if(p!==page)p.close().catch(()=>{})});await page.route('**/*',async route=>{const req=route.request(),method=req.method().toUpperCase(),url=new URL(req.url());if(url.origin!==spec.origin||!SAFE_METHODS.has(method))return route.abort('blockedbyclient');return route.continue()});page.on('dialog',d=>d.dismiss().catch(()=>{}));const start=safeUrl(spec.origin,spec.journey.startPath);let nav=await page.goto(start,{waitUntil:'domcontentloaded',timeout:10000});httpStatus=nav?.status()||null;
  for(const s of spec.journey.steps){lastStep={index:Number(s.index)||null,action:clean(s.action,40),label:clean(s.label,100)||null};if(s.action==='navigate'){const u=safeUrl(spec.origin,s.path);nav=await page.goto(u,{waitUntil:'domcontentloaded',timeout:10000});httpStatus=nav?.status()||null}else if(s.action==='assert-visible'){await page.locator(s.selector).first().waitFor({state:'visible',timeout:5000})}else if(s.action==='click-link'){const loc=page.locator(s.selector).first();const href=await loc.getAttribute('href');const dest=href?safeUrl(spec.origin,href):null;if(!dest)throw new Error('Link does not resolve to an approved same-origin destination');await Promise.all([page.waitForLoadState('domcontentloaded',{timeout:10000}).catch(()=>{}),loc.click({timeout:5000})]);if(new URL(page.url()).origin!==spec.origin)throw new Error('Navigation left the approved origin')}else if(s.action==='click-control'){const loc=page.locator(s.selector).first();if(await loc.getAttribute('data-weaverelay-safe-action')===null)throw new Error('Control is not marked safe for WeaveRelay');await loc.click({timeout:5000});if(new URL(page.url()).origin!==spec.origin)throw new Error('Control navigation left the approved origin')}else if(s.action==='wait-for-url'){const target=safeUrl(spec.origin,s.path);await page.waitForURL(u=>u.href.split('#')[0]===target,{timeout:8000})}}
  return{status:'PASS',journeyId:spec.journey.id,name:spec.journey.name,lastStep,url:page.url(),httpStatus,javascriptError,networkFailure,browserReplayProven:true}
 }catch(e){return{status:'FAIL',journeyId:spec.journey.id,name:spec.journey.name,failedStep:lastStep,url:page?.url()||spec.origin,httpStatus,javascriptError,networkFailure,browserReplayProven:true,reason:clean(e?.message||'Guarded browser journey failed',240)}}finally{await browser.close().catch(()=>{})}}
const server=http.createServer(async(req,res)=>{if(req.method==='GET'&&req.url==='/health')return response(res,200,{ok:true,runner:'weaverelay-playwright',browserReplayProven:true});if(req.method!=='POST'||req.url!=='/run')return response(res,404,{ok:false});if(!TOKEN||req.headers.authorization!==`Bearer ${TOKEN}`)return response(res,401,{ok:false,error:'unauthorized'});let raw='';for await(const c of req){raw+=c;if(raw.length>100000){req.destroy();return}}let body;try{body=JSON.parse(raw)}catch{return response(res,400,{ok:false,error:'invalid_json'})}const spec=validate(body);if(!spec)return response(res,409,{ok:false,error:'journey_not_safe'});const result=await Promise.race([run(spec),new Promise(r=>setTimeout(()=>r({status:'FAIL',journeyId:spec.journey.id,name:spec.journey.name,browserReplayProven:true,reason:'Guarded browser journey exceeded 30 seconds'}),30000))]);return response(res,200,result)});
server.listen(PORT,'0.0.0.0',()=>console.log(`WeaveRelay browser runner listening on ${PORT}`));
